# Generated by Django 2.2.1 on 2019-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
