# Generated by Django 2.2.1 on 2019-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='bandup/media/default.jpg', upload_to='profile_pics'),
        ),
    ]
