# Generated by Django 2.2.1 on 2019-09-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='head_image',
            new_name='profile_image',
        ),
    ]
