# Generated by Django 2.2.1 on 2019-09-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190922_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_image',
            new_name='teacher_image',
        ),
    ]
