# Generated by Django 2.2.1 on 2019-09-24 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_teacher_teaching_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
